Vehical.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Vehicle.Model;

namespace Vehical.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vehical.Web/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using Vehicle.Dal.Infrastructure.IRepository;
using Vehicle.Model;
using System.IO;
using ExcelDataReader;
using System.Text;
using Microsoft.AspNetCore.Http;
using Vehicle.Dal.Helper;
using Vehicle.Dal;
using Microsoft.EntityFrameworkCore;

namespace Vehicle.Web.Controllers
{
    public class VehicleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDBContext _context;

       
        public VehicleController(IUnitOfWork unitOfWork, ApplicationDBContext context)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }
        [HttpGet]

        public async Task<IActionResult> Index(int? pageNumber)
        {
               vehicle v= new vehicle();
            //Pagination 
              try
              {
                int pageSize = 8;
                var vehicles = await _unitOfWork.vehicle.GetAll();
                    //await _unitOfWork.vehicle.GetAll();
                return View(Paginated<vehicle>.Create(vehicles, pageNumber ?? 1, pageSize));
              }
              catch(Exception ex) { 
                string message = ex.Message;
              }
              return View();
            
         }

        [HttpGet]
        public IActionResult UploadVehiclesFromExcel()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UploadVehiclesFromExcel(IFormFile file, vehicle v)
        {
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            //File Upload Code in our projects public directory
            try
            {
                if (file != null && file.Length > 0)
                {
                    var uploadFolder = $"{Directory.GetCurrentDirectory()}\\wwwroot\\Uploads\\";
                    if (!Directory.Exists(uploadFolder))
                    {
                        Directory.CreateDirectory(uploadFolder);
                    }
                    var filePath = Path.Combine(uploadFolder, file.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);

                    }
                    using (var stream = System.IO.File.Open(filePath, FileMode.Open, FileAccess.Read))
                    {
                        using (var reader = ExcelReaderFactory.CreateReader(stream))
                        {
                            do
                            {
                            bool isHeaderSkiped = false;

                            while (reader.Read())
                                {
                                if (!isHeaderSkiped)
                                {
                                    isHeaderSkiped = true;
                                    continue;
                                }
                                    // v = vehicle instance

                                    v.RegNo = reader.GetValue(1).ToString();
                                    v.Make = reader.GetValue(2).ToString();
                                    v.Model = reader.GetValue(3).ToString();
                                    v.Color = reader.GetValue(4).ToString();
                                    v.EngineNo = reader.GetValue(5).ToString();
                                    v.ChasisNo = reader.GetValue(6).ToString();
                                    v.DateOfPurchase = reader.GetValue(7).ToString();

                                    //Data Save Into Database
                                    _unitOfWork.vehicle.Add(v);
                                    v.Active = true;
                                    _unitOfWork.Save();
                                    TempData["Success"] = "Data Inserted Successfully into Database...";
                                    return RedirectToAction("Index");
                                }

                            } while (reader.NextResult());
                        }
                    }

                }

            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }


            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }
                vehicle Vehicle = await _unitOfWork.vehicle.GetOneRecord(x => x.Id == id);
                if (Vehicle == null)
                {
                    return NotFound();
                }
                return View(Vehicle);
            }
            catch(Exception ex) { 
            string message = ex.Message;
            }
            return View();
        }
        [HttpPost]
        public IActionResult Edit(vehicle Vehicle)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.vehicle.Update(Vehicle);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }catch (Exception ex)
                {
                    string message=ex.Message;
                }
                
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }
                vehicle Vehicle = await _unitOfWork.vehicle.GetOneRecord(x => x.Id == id);
                if (Vehicle == null)
                {
                    return NotFound();
                }
                return View(Vehicle);
            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }
            return View();
        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteData(int? id)
        {
            try
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }
                var deleteVehicle = await _unitOfWork.vehicle.GetOneRecord(vehicle => vehicle.Id == vehicle.Id);
                if (deleteVehicle == null)
                {
                    return NotFound();
                }
                _unitOfWork.vehicle.Delete(deleteVehicle);
                deleteVehicle.Active = false;
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                string message=ex.Message; 
            }
          return View() ;
        }
    }
}

Vehical.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">VEHICLE DATA PORTAL</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core" class="text-decoration-none">Retrieving Data from Excel File and Save into MSSQL Database</a>.</p>
</div>

Vehical.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vehical App</title>
    <link rel="stylesheet" href="~/css/MorphBootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vehical.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  
</head>
<body>
    <header class="mb-5">
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand " asp-action="Index" asp-controller="Home"><i class="bi bi-truck"></i> VEHICLES</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto ml-5">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Vehicle" asp-action="Index"><i class="bi bi-truck-front-fill"></i> Vehicles</a>
                        </li>
                     
                </div>
            </div>
        </nav>
      
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center text-primary">
            &copy; 2023 - My Vehicles @* <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Vehical.Web/Views/Vehicle/Delete.cshtml
@model vehicle
@{
    ViewData["Title"] = "Delete";
}
<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Delete Vehicle</h2>
    </div>

    <form method="post" asp-action="Edit">
        <input type="hidden" asp-for="Id"/>
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="RegNo">Registraion No</label>
                <input type="text" class="form-control mb-3" asp-for="RegNo" disabled>
                <span asp-validation-for="RegNo" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Make">Created Year</label>
                <input type="text" class="form-control mb-3" asp-for="Make" disabled>
                <span asp-validation-for="Make" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Model">Model</label>
                <input type="text" class="form-control mb-3" asp-for="Model" disabled>
                <span asp-validation-for="Model" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Color">Color</label>
                <input type="text" class="form-control" asp-for="Color" disabled>
                <span asp-validation-for="Color" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="EngineNo">Engine No</label>
                <input type="text" class="form-control mb-3" asp-for="EngineNo" disabled>
                <span asp-validation-for="EngineNo" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="ChasisNo">Chasis On</label>
                <input type="text" class="form-control" asp-for="ChasisNo" disabled>
                <span asp-validation-for="Color" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="DateOfPurchase">Date of Purchase</label>
                <input type="datetime-local" class="form-control mb-3" asp-for="DateOfPurchase" disabled>
                <span asp-validation-for="DateOfPurchase" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Active">Active</label>
                <input type="text" class="form-control" asp-for="Active" disabled>
                <span asp-validation-for="Active" class=" alert-danger"></span>
            </div>
        </div>

        <input asp-action="Delete" asp-controller="Vehicle" class="btn btn-primary text-primary" value="Delete" type="submit" />
        @*<button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Update</button>*@
        <a asp-controller="Vehicle" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To Vehicle</a>
    </form>

</div>

Vehical.Web/Views/Vehicle/Edit.cshtml
@model vehicle
@{
    ViewData["Title"] = "Edit";
}
<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Edit Vehicle</h2>
    </div>

    <form method="post" asp-action="Edit">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="RegNo">Registraion No</label>
                <input type="text" class="form-control mb-3" asp-for="RegNo">
                <span asp-validation-for="RegNo" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Make">Created Year</label>
                <input type="text" class="form-control mb-3" asp-for="Make">
                <span asp-validation-for="Make" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Model">Model</label>
                <input type="text" class="form-control mb-3" asp-for="Model">
                <span asp-validation-for="Model" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Color">Color</label>
                <input type="text" class="form-control" asp-for="Color">
                <span asp-validation-for="Color" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="EngineNo">Engine No</label>
                <input type="text" class="form-control mb-3" asp-for="EngineNo">
                <span asp-validation-for="EngineNo" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="ChasisNo">Chasis On</label>
                <input type="text" class="form-control" asp-for="ChasisNo">
                <span asp-validation-for="Color" class=" alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="DateOfPurchase">Date of Purchase</label>
                <input type="datetime-local" class="form-control mb-3" asp-for="DateOfPurchase">
                <span asp-validation-for="DateOfPurchase" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Active">Active</label>
                <input type="text" class="form-control" asp-for="Active">
                <span asp-validation-for="Active" class=" alert-danger"></span>
            </div>
        </div>

        <input asp-action="Edit" asp-controller="Vehicle" class="btn btn-primary text-primary" value="Update" type="submit"/>
       @* <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Update</button>*@
        <a asp-controller="Vehicle" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To Vehicle</a>
    </form>

</div>

Vehical.Web/Views/Vehicle/Index.cshtml
@model Paginated<vehicle>
@{
    ViewData["Title"] = "Index";
}
@*<div class="w-100 m-6">
    <h1 class="text-center m-10 text-primary">Vehicles Details</h1>
</div>*@

<div class="container p-3">
    <p class="text-center text-success font-weight-bold">@TempData["Success"]</p>
    <div class="row p-2 ">
        <div class="col-4">
            <h3 class="text-primary">VEHICLES DETAILS</h3>
        </div>
        <div class="col-4">
            <a class="btn btn-primary text-primary" asp-controller="Vehicle" asp-action="UploadVehiclesFromExcel"><i class="bi bi-plus-circle"></i> Add New</a>
        </div>
        <div class="col-4">
           
            <form method="get" class="d-flex">
                <input  asp-action="Index" name="SearchTerm" asp-controller="Vehicle" class="form-control text-primary me-sm-2" type="search" placeholder="Search Vehicle">
                <a asp-action="Index" asp-controller="Vehicle" class="btn btn-secondary text-primary my-2 my-sm-0" type="submit" id="searchBtn"><i class="bi bi-search"></i></a>
            </form>
        </div>

    </div>

</div>

<div class="container mt-1">
    <table class="table table-bordered border="1" table-striped table-hover" style="width:100%">
        <thead>
            <tr>
                <th>
                    Registration No
                </th>
                <th>
                    Make
                </th>
                <th>
                    Model
                </th>
                <th>
                    Color
                </th>
                <th>
                    Engine No
                </th>
                <th>
                    Chasis No
                </th>
                <th>
                    Date of Purchase
                </th>
                <th>
                    Active
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        @item.RegNo
                    </td>
                    <td>
                        @item.Make
                    </td>
                    <td>
                        @item.Model
                    </td>
                    <td>
                        @item.Color
                    </td>
                    <td>
                        @item.EngineNo
                    </td>
                    <td>
                        @item.ChasisNo
                    </td>
                    <td>
                        @item.DateOfPurchase
                    </td>
                    <td>
                        @item.Active
                    </td>
                    <td role="group">
                        <a asp-action="Edit" asp-controller="Vehicle" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                        <a asp-action="Delete" asp-controller="Vehicle" asp-route-id="@item.Id"><i class="bi bi-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@{
    var prevDisable = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisable = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="Index" asp-route-pageNumber="@(Model.pageIndex-1)" class="btn btn-default text-primary @prevDisable">Previous</a>
<a asp-action="Index" asp-route-pageNumber="@(Model.pageIndex+1)" class="btn btn-default text-primary @nextDisable">Next</a>

Vehical.Web/Views/Vehicle/UploadVehiclesFromExcel.cshtml
@{
    ViewData["Title"] = "UploadVehiclesFromExcel";
}

<h1 class="text-center text-primary">Upload File</h1>

<div>
    <a asp-action="Index" asp-controller="Vehicle" class="text-decoration-none text-primary btn btn-primary"><i class="bi bi-arrow-left-circle"></i> Back to Vehicle</a>
</div>

<form method="post" asp-action="UploadVehiclesFromExcel" asp-controller="Vehicle" enctype="multipart/form-data">

    @*<div class="row">
        <label class="text-primary">Select Excel FIle</label>
        <input type="file" name="file" placeholder="Select File" class="text-primary"/>
    </div>*@
    <div class="d-flex align-items-center justify-content-center flex-column w-80 border-1 border-black">
        <div class="form-group row">
            <label for="formFile" class="form-label mt-4 text-primary">Input Excel File From Your Device</label>
            <input class="form-control" type="file" name="file" id="formFile" accept=".xlsx,.xls" required>
        </div>
        <br />
        <div class="row">
            <div class="col-3">
                <input type="submit" asp-action="UploadVehiclesFromExcel" asp-controller="Vehicle" class="btn btn-dark text-primary" value="Upload File" />
            </div>
        </div>
    </div>
   


</form>